### ISSUE TITLE
Add PresenceViewer

### ISSUE THREAD

**Issue by okdistribute** [getditto/DittoSwiftPackage#13]
It would be nice if this was available through the SwiftPM because customers often need it to debug

**Comment by phatblat** [comment]
Yep, for sure! Having a 2nd library makes a stronger case for create a Swift package collection which makes it even easier to see all of our packages.

**Comment by phatblat** [comment]
The presence viewer was added to [DittoSwiftTools](https://github.com/getditto/DittoSwiftTools) in getditto/DittoSwiftTools#7
